### ISSUE TITLE
npm i pinia  report error

### ISSUE THREAD

**Issue by Olaf0509** [vuejs/pinia#2600]
### Reproduction

1

### Steps to reproduce the bug

node version v18.19.1
npm version 10.2.4
1、npm create vite@latest my-vue-app -- --template vue
2、cd my-vue-app
3、npm i pinia

### Expected behavior

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-vue-app@0.0.0
npm ERR! Found: vue@3.4.21
npm ERR! node_modules/vue
npm ERR!   vue@"^3.3.11" from the root project
npm ERR!   peer vue@"^2.6.14 || ^3.3.0" from pinia@2.1.7
npm ERR!   node_modules/pinia
npm ERR!     pinia@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.4.0" from pinia@2.1.7
npm ERR!   node_modules/pinia
npm ERR!     pinia@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Actual behavior

1

**Comment by posva** [comment]
Search existing issues before opening new ones. This has already been opened
