### ISSUE TITLE
__vite_ssr_import_0__.xxx is not a function

### ISSUE THREAD

**Issue by baixiaoyu2997** [vuejs/pinia#2626]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-i3vypr?file=composables%2FuseContract.ts

### Steps to reproduce the bug

pnpm run dev

### Expected behavior

can start dev server

### Actual behavior

can't start dev server

### Additional information

according to my tests, this problem is related to the `composables/useContract` function. It should be caused by the fact that `useContract` has the same name as the parameter in `sdk/util/common.ts`. When I try to delete `default` in `useContract` After that, this error will not occur. This may also be related to the logic of auto-import.

**Comment by posva** [comment]
Please, next time consider using the [Discord server](https://chat.vuejs.org/), Discussions (if enabled in this repository), or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by baixiaoyu2997** [comment]
yes, i will. I thought this might be a bug in `nuxt` or `vite-node`, so I closed the issue and created an issue in nuxt repo: https://github.com/nuxt/nuxt/issues/26543
