### ISSUE TITLE
Chrome 128 hmr tab crash

### ISSUE THREAD

**Issue by Syiana** [vuejs/pinia#2761]
### Reproduction

-

### Steps to reproduce the bug

1. create fresh vue project with 'npm create vue@latest'
2. select pinia store
3. import the store to the starter file
4. change something in the store file and save it
5. crash (sometimes it does not crash but the changes are not active)

### Expected behavior

-

### Actual behavior

-

**Comment by posva** [comment]
I'm deleting this issue because it lacks absolutely everything needed to get any help, even as a discussion, and I don't want it to bloat search results. Use Discussions or the Vue.js Discord if you want help. Thanks!
